blank_issues_enabled: false

contact_links:
  - name: 📚 Project Documentation
    url: https://github.com/spzvtbg/MyPortfolio/tree/master/docs
    about: Check the project documentation before creating an issue.