name: ✨ Feature Request
description: Implement a new feature or enhancement.
title: "[Feature]: "

body:
  - type: textarea
    id: objective
    attributes:
      label: Objective
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      placeholder: |
        - [ ] Feature implemented
        - [ ] Tested
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes